### ISSUE TITLE
Issue with ETH payment 

### ISSUE THREAD

**Issue by momoDragon** [ShoppyGG/shoppy-woocommerce#3]
ORDER ID
`8e34ff79-9dd8-4708-850b-16d43e52c4c0
`
PAYMENT METHOD

> ETH

TRANSACTION: 

> https://etherscan.io/tx/0x5d71ade5d066494388790a8e4a11850e8ee408ed9cb660d397c8f7ebe1854c7f

Transaction completed but order not placed.

**Comment by finndev** [comment]
The order is now completed and paid out. Contact support AT shoppy DOT gg next time for a faster response.
