### ISSUE TITLE
error - how to resolve

### ISSUE THREAD

**Issue by softnwords** [ShoppyGG/shoppy-woocommerce#4]
order_key was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Shoppy->process_payment, WC_Gateway_Shoppy->generate_shoppy_payment, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.

**Comment by finndev** [comment]
A new version has been released and tested. Can you test it now? @softnwords
